apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Port the service is exposed on internally
      targetPort: 80   # Port in the container
      nodePort: 30080  # Port exposed on the node
  type: NodePort


